workflows:

  ios-native-quick-start:

    name: QXQ26

    max_build_duration: 120

    instance_type: mac_mini_m2

    integrations:
      app_store_connect: PlantPulse

    environment:

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.KilnTracebiaomianzudi.cn

      vars:
        BUNDLE_ID: $bundle_identifier
        PROJECT_PATH: "QXQ/ios-chat.xcworkspace"
        XCODE_WORKSPACE: "$PROJECT_PATH/ios-chat.xcworkspace"
        XCODE_SCHEME: "ios-chat"
        APP_STORE_APPLE_ID: 6809854010

      xcode: latest


    scripts:

      - name: Set up provisioning profiles settings on Xcode project
        script: |
          xcode-project use-profiles


      - name: Increment build number
        script: |
          cd "$PROJECT_PATH"

          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")

          echo "Current build: $LATEST_BUILD_NUMBER"

          NEXT_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))

          echo "New build: $NEXT_BUILD_NUMBER"

          agvtool new-version -all "$NEXT_BUILD_NUMBER"


      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"


    artifacts:

      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM


    publishing:

      email:
        recipients:
          - 985446278@qq.com
          - user_2@example.com

        notify:
          success: true
          failure: false


      app_store_connect:

        auth: integration

        submit_to_testflight: true

        submit_to_app_store: false
